### ISSUE TITLE
Disable notifications during the weekend

### ISSUE THREAD

**Issue by xates** [albertoxamin/unimeal-bot#3]
Please disable notifications on Sundays since all the canteens are closed on this day and add an option to disable notifications for Saturdays too if not interested, since only Tommaso Gar is open on Saturday.

**Comment by albertoxamin** [comment]
@xates If you look on the menu you will find menus even for Sundays 
https://www.operauni.tn.it/documents/10603/20928/Menù+settimanale+PASTO+a+SCELTA/dd3acf39-dfcb-4101-ab0b-a934f6bd54c6?version=1.1

**Comment by xates** [comment]
Yes, I know, however if you look at the schedules of the canteens there is no canteen open on Sundays. I suspect it is an error in the menu. Anyhow it would be an useful feature to be able to disable notifications for weekends. Please let me know if you are willing to support such a feature. Thanks
